server:
  port: 8080
app:
  name: etl
spring:
  mvc:
    servlet:
      path: /etl
datasource:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/etl?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Hongkong
  username: root
  password: root